# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 078a33835742bd3e3ba0432065cd007b37fa5bfcb456bca9922f3ae0d01ef3298b8cfd3410dd4a1ebea57db8c99d535e8af80dec4443521049e6f663f3aa7a89

test:
  secret_key_base: fa3f0bc4cf718d36a0ac09fd97c11e0d63433cc000ae48801be3872485f30959cb9bdc89909b9201f27b7e5f4737da6c6f62d97d871c4bcd20b59ab9eaf26477

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
